FROM ubuntu:latest
MAINTAINER jeffrey <hevei.ho@gmail.com>

# proxy setting (replace proxy.company.net with your coporate proxy)
#RUN echo 'Acquire::http::proxy "http://proxy.company.net:8000";' >> /etc/apt/apt.conf.d/01proxy
#ENV http_proxy http://proxy.company.net:8000
#ENV https_proxy https://proxy.company.net:8000

# Install the update
RUN apt-get -y update && apt-get -y upgrade

# Install git/wget/jdk/maven
RUN apt-get install -y git wget default-jdk maven

# Install NVML library with tag 0.1+b16
RUN git clone https://github.com/pmem/nvml.git && cd nvml && git checkout tags/0.1+b16 && make && make install

# Install PMalloc
RUN git clone https://github.com/NonVolatileComputing/pmalloc.git && cd pmalloc && make && make install

# Build Mnemonic
RUN git clone https://github.com/apache/incubator-mnemonic.git && cd incubator-mnemonic && git clean -xdf && mvn clean package install

###########
#download spark v1.6.0
#RUN git clone https://github.com/apache/spark.git && git checkout tags/v1.6.0
#WORKDIR spark

#build spark
#RUN build/mvn -DskipTests clean package
############
